#!/bin/sh

make clean && ./configure.gnu && make &&
/usr/local/sbin/checkinstall -D --nodoc --maintainer=ksquirrel@tut.by \
--requires="liblcms1, libjpeg62, libopenexr2c2a, libmng1, libpng12-0, transfig, netpbm, djvulibre-bin, libfreetype6, libjasper-1.701-1, libtiff4, libungif4g, libwmf0.2-7, librsvg2-bin, medcon, zlib1g" \
--pkglicense=LGPL --backup=no --pkgrelease=3etch