#!/bin/sh

rm -rf autom4te.cache

make distclean

cd contrib

for i in libpixman libsvg libsvg-cairo cairo libwmf;
do cd $i && rm -rf autom4te.cache && rm -f install-sh aclocal.m4 configure config.h.in config.log libtool missing stamp-h1 config.status ltmain.sh config.guess config.sub depcomp Makefile config.h && cd ..;
done
