#!/bin/sh

rm -f libkls_ttx.so

g++ -I. -I../include -Wall -O2 -fPIC -c fmt_codec_ttx.cpp
g++ -I. -I../include -Wall -O2 -fPIC -c ../kls_lib/fileio.cpp
g++ -Wall -shared fileio.o fmt_codec_ttx.o -o libkls_ttx.so
rm -f fmt_codec_ttx.o fileio.o