#!/bin/sh

# internal script.
#
# generates fmt_filters' distribution
#

F=`cat fmt_filters_VERSION | head -n 1`
FDIR="fmt_filters-$F"

mkdir $FDIR

cp fmt_filters_VERSION   $FDIR/VERSION
cp fmt_filters_README    $FDIR/README
cp fmt_filters_ChangeLog $FDIR/Changelog
cp fmt_filters.h         $FDIR
cp fmt_filters.cpp       $FDIR
cp ../COPYING            $FDIR

rm -f ${FDIR}.tar.gz

GZIP=--best tar cvfz ${FDIR}.tar.gz $FDIR

rm -rf $FDIR
