#!/bin/sh

for i in avs bmp camera cut fli gif hdr ico iff jbig jpeg jpeg2000 koala lif mac mdl mng msp mtv openexr pcx pix png pnm psd pxr ras rawrgb sct sgi sun svg tga tiff ttf utah wal wbmp wmf xbm xcur xpm xwd djvu dxf neo leaf pi1 xim pict;
do echo $i && cd kls_$i && touch -m * && cd ..;
done
