#!/bin/sh

for i in avs bmp camera cut fli gif hdr ico iff fig jbig jpeg jpeg2000 koala lif mac mdl mng msp mtv openexr pcx pix png pnm psd pxr ras rawrgb sct sgi sun svg tga tiff ttf utah wal wbmp wmf xbm xcur xpm xwd djvu dxf neo leaf pi1 pi3 xim pict;
do mcedit kls_$i/Makefile.am ;
done
