#!/bin/sh

for i in bmp camera cut fli gif hdr ico iff jpeg jpeg2000 koala lif mdl openexr pcx pix png pnm psd ras rawrgb sct sgi sun svg tga tiff utah wal wbmp wmf xbm xcur xpm xwd;
do kwrite $i/fmt_codec_$i.cpp ;
done
