#!/bin/sh

for i in avs bmp camera cut fli gif hdr ico iff jpeg jpeg2000 koala lif mac mdl msp mtv openexr pcx pix png pnm psd pxr ras rawrgb sct sgi sun svg tga tiff utah wal wbmp wmf xbm xcur xpm xwd;
do kwrite $i/fmt_codec_$i.cpp ;
done
