#!/bin/sh

# create symlinks from all codecs (bmp/.libs/libSQ_codec_bmp.so, ...)
# to /usr/lib/ksquirrel-libs/
#
# Can be used by developers
#
# Usage:
#  $ cd ksquirrel-libs/kernel/
#  $ ./link
#

KSQUIRREL_LIBS="/usr/lib/ksquirrel-libs/"

rm -f $KSQUIRREL_LIBS/*

mkdir $KSQUIRREL_LIBS > /dev/null 2>&1

for i in avs bmp camera cut fli gif hdr ico iff jpeg jpeg2000 koala lif mac mdl msp mtv openexr pcx pix png pnm psd pxr ras rawrgb sct sgi sun svg tga tiff utah wal wbmp wmf xbm xcur xpm xwd;
do echo "Linking libSQ_codec_$i.so ..." && ln -s `pwd`/$i/.libs/libSQ_codec_$i.so $KSQUIRREL_LIBS;
done

ln -s `pwd`/xpm/rgbmap $KSQUIRREL_LIBS
ln -s `pwd`/../VERSION $KSQUIRREL_LIBS/version