######################################################################
# Automatically generated by qmake (1.06c) Thu Mar 3 00:43:05 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .
INCLUDEPATH += ../../kernel

# Input
HEADERS += myqgl.h
SOURCES += main.cpp myqgl.cpp ../../kernel/fmt_utils.cpp
LIBS    += -lGL -lGLU