######################################################################
# Automatically generated by qmake (1.06c) Thu Mar 3 02:54:53 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .
INCLUDEPATH += ../../kernel

# Input
HEADERS += myqt.h
SOURCES += main.cpp myqt.cpp
